adding 5min time for the e2e tests

diff --git a/.github/workflows/e2e_lighthouse_performance_acceptance_tests.yml b/.github/workflows/e2e_lighthouse_performance_acceptance_tests.yml
--- a/.github/workflows/e2e_lighthouse_performance_acceptance_tests.yml
+++ b/.github/workflows/e2e_lighthouse_performance_acceptance_tests.yml
@@ -76,24 +76,6 @@ jobs:
             requirements_dev.in
             requirements_dev.txt
       - uses: ./.github/actions/merge
-      # - name: Cache node modules
-      #   uses: actions/cache@v3
-      #   env:
-      #     cache-name: cache-node-modules
-      #   with:
-      #     path: /home/runner/work/oppia/yarn_cache
-      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
-      #     restore-keys: |
-      #       ${{ runner.os }}-build-${{ env.cache-name }}-
-      #       ${{ runner.os }}-build-
-      #       ${{ runner.os }}-
-      # - name: Attempt to download build files artifact
-      #   id: download_artifact_1
-      #   uses: actions/download-artifact@v3
-      #   continue-on-error: true
-      #   with:
-      #     name: build_files
-      #     path: /home/runner/work/oppia/
       - name: Install Python deps
         run: |
           pip install --require-hashes --no-deps -r requirements.txt
@@ -107,18 +89,6 @@ jobs:
         run: |
           sudo rm -rf /usr/share/dotnet
           sudo rm -rf "$AGENT_TOOLSDIRECTORY"
-      # - name: (Artifact re-build) Cache third_party/static
-      #   if: steps.download_artifact_1.outcome == 'failure'
-      #   uses: actions/cache@v3
-      #   env:
-      #     cache-name: cache-node-modules
-      #   with:
-      #     path: /home/runner/work/oppia/oppia/third_party/static
-      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('dependencies.json') }}
-      #     restore-keys: |
-      #       ${{ runner.os }}-build-${{ env.cache-name }}-
-      #       ${{ runner.os }}-build-
-      #       ${{ runner.os }}-
       - name: Initializing Containers
         run: |
           sudo make build
@@ -128,8 +98,16 @@ jobs:
         run: |
           sudo chmod -R 777 /home/runner/work/oppia/oppia
           sudo xvfb-run -a --server-args="-screen 0, 1285x1000x24" make run_tests.e2e suite=${{ matrix.suite }}
+        continue-on-error: true
         env:
           VIDEO_RECORDING_IS_ENABLED: 0
+      - name: Check on failures
+        if: steps.hello.outcome != 'success' || steps.world.outcome != 'success'
+        run: |
+          echo "--- E2E tests suite ${{ matrix.suite }} failed ---"
+          echo "--- Waiting for 5 minutes before exiting all the other e2e suites ---"
+          sleep 300
+          exit 1
       - name: Uploading webdriverio-video as Artifacts
         if: ${{ failure() }}
         uses: actions/upload-artifact@v3
@@ -142,12 +120,6 @@ jobs:
         with:
           name: webdriverio-screenshots
           path: /home/runner/work/oppia/webdriverio-screenshots
-      # - name: Uploading webpack bundles as an artifact
-      #   if: ${{ failure() }}
-      #   uses: actions/upload-artifact@v3
-      #   with:
-      #     name: webpack-bundles
-      #     path: /home/runner/work/oppia/oppia/build
       - name: Report failure if failed on oppia/oppia develop branch
         if: ${{ failure() && github.event_name == 'push' && github.repository == 'oppia/oppia' && github.ref == 'refs/heads/develop'}}
         uses: ./.github/actions/send-webhook-notification
