checking fail-fast property

diff --git a/.github/workflows/e2e_lighthouse_performance_acceptance_tests.yml b/.github/workflows/e2e_lighthouse_performance_acceptance_tests.yml
--- a/.github/workflows/e2e_lighthouse_performance_acceptance_tests.yml
+++ b/.github/workflows/e2e_lighthouse_performance_acceptance_tests.yml
@@ -1,20 +1,22 @@
 name: End-to-End, Lighthouse CI performance and Acceptance tests
-on:
-  merge_group:
-    types: [checks_requested]
-  push:
-    branches:
-      - develop
-      - release-*
-  pull_request:
-    branches:
-      - develop
-      - release-*
+on: [push]
+# on:
+#   merge_group:
+#     types: [checks_requested]
+#   push:
+#     branches:
+#       - develop
+#       - release-*
+#   pull_request:
+#     branches:
+#       - develop
+#       - release-*
 
 jobs:
   e2e_test:
     runs-on:  ${{ matrix.os }}
     strategy:
+      fail-fast: false
       matrix:
         os: [ubuntu-22.04]
         suite:
@@ -97,17 +99,17 @@ jobs:
         run: |
           sudo chmod -R 777 /home/runner/work/oppia/oppia
           sudo xvfb-run -a --server-args="-screen 0, 1285x1000x24" make run_tests.e2e suite=${{ matrix.suite }}
-        continue-on-error: true
+        # continue-on-error: true
         env:
           VIDEO_RECORDING_IS_ENABLED: 0
-      - name: Check on failures
-        if: steps.e2e_suite.outcome != 'success'
-        # Waiting for ~15minutes is because we are waiting for the other e2e suites before exiting. By this, we are not stopping all the other suites if any flaky test fails.
-        run: |
-          echo "--- E2E tests suite ${{ matrix.suite }} failed. Check the above step for the logs. ---"
-          echo "--- Waiting before exiting all the other e2e suites ---"
-          sleep 1000
-          exit 1
+      # - name: Check on failures
+      #   if: steps.e2e_suite.outcome != 'success'
+      #   # Waiting for ~15minutes is because we are waiting for the other e2e suites before exiting. By this, we are not stopping all the other suites if any flaky test fails.
+      #   run: |
+      #     echo "--- E2E tests suite ${{ matrix.suite }} failed. Check the above step for the logs. ---"
+      #     echo "--- Waiting before exiting all the other e2e suites ---"
+      #     sleep 1000
+      #     exit 1
       - name: Uploading webdriverio-video as Artifacts
         if: ${{ failure() }}
         uses: actions/upload-artifact@v3
