Address comments.

diff --git a/.github/workflows/stress_test_acceptance_test.yml b/.github/workflows/stress_test_acceptance_test.yml
--- a/.github/workflows/stress_test_acceptance_test.yml
+++ b/.github/workflows/stress_test_acceptance_test.yml
@@ -42,7 +42,7 @@ jobs:
           if [ "$NUM_RUNS" -gt 128 ]; then
             echo "Error: num_runs exceeds 128" >&2
             exit 1
-          fi          
+          fi
 
           MATRIX=$(seq 1 "$NUM_RUNS" | jq -R . | jq -s -c .)
           echo "matrix=$MATRIX" >> "$GITHUB_OUTPUT"
@@ -73,10 +73,10 @@ jobs:
       - name: Sanitize test_suite input
         run: |
           if [[ "$TEST_SUITE" =~ [^a-zA-Z/-] ]]; then
-          echo "TEST_SUITE contains invalid characters (only letters, slashes, and dashes allowed)."
-          exit 1
+            echo "TEST_SUITE contains invalid characters (only letters, slashes, and dashes allowed)."
+            exit 1
           else
-          echo "TEST_SUITE is valid."
+            echo "TEST_SUITE is valid."
           fi
       - name: Checkout repository so that local actions can be used
         uses: actions/checkout@v4
@@ -88,7 +88,7 @@ jobs:
         id: generate_suite_name_for_artifacts
         # Replace slashes in the filename with underscores.
         run: |
-          SUITE_NAME=${{ inputs.test_suite }}-${{ matrix.run }}-${{ matrix.mobile && 'mobile' || 'desktop' }}
+          SUITE_NAME=$TEST_SUITE-${{ matrix.run }}-${{ matrix.mobile && 'mobile' || 'desktop' }}
           echo "MODIFIED_SUITE_NAME=${SUITE_NAME//\//_}" >> $GITHUB_OUTPUT
       - name: Run ${{ matrix.mobile && 'Mobile' || 'Desktop' }} Acceptance Test
         uses: ./.github/actions/run-acceptance-tests
